# Generated by Django 5.0 on 2023-12-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('branch_location', models.CharField(choices=[('', 'Select Branch Location'), ('Borivali', 'Borivali'), ('Andheri', 'Andheri'), ('Malad', 'Malad')], default='', max_length=50)),
                ('photo', models.ImageField(upload_to='manager_photos/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course_content', models.FileField(upload_to='course_content/')),
                ('video', models.FileField(upload_to='course_videos/')),
                ('e_book', models.FileField(upload_to='e_books/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('course_enrolled', models.CharField(choices=[('Data Science', 'Data Science'), ('Full stack', 'Full stack')], max_length=20)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('nationality', models.CharField(max_length=50)),
                ('upload_resume', models.FileField(upload_to='resumes/')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('signature', models.ImageField(upload_to='signatures/')),
                ('branch_location', models.CharField(choices=[('', 'Select Branch Location'), ('Borivali', 'Borivali'), ('Andheri', 'Andheri'), ('Malad', 'Malad')], default='', max_length=50)),
                ('password', models.CharField(default='', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('photo', models.ImageField(upload_to='professor_photos/')),
                ('branch_location', models.CharField(choices=[('', 'Select Branch Location'), ('Borivali', 'Borivali'), ('Andheri', 'Andheri'), ('Malad', 'Malad')], default='', max_length=50)),
                ('courses_teaching', models.ManyToManyField(to='KnowledgeNest.course')),
            ],
        ),
    ]
