# Generated by Django 5.0 on 2023-12-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeNest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchmanager',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professor',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
