# Generated by Django 5.0 on 2023-12-17 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeNest', '0002_branchmanager_number_professor_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='courses_teaching',
        ),
        migrations.AddField(
            model_name='professor',
            name='courses_teaching',
            field=models.CharField(default='', max_length=50),
        ),
    ]
