# Generated by Django 4.2.7 on 2023-12-21 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeNest', '0004_studentlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentlog',
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
