# Generated by Django 5.0 on 2023-12-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KnowledgeNest', '0007_student_id_alter_student_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('video_file', models.FileField(upload_to='video/')),
            ],
        ),
    ]
